### ISSUE TITLE
Crash upon creating and generating world

### ISSUE THREAD

**Issue by jacobmoerch** [ExDrill/CaveEnhancementsMod#1]
Mod list is included in crash log.

[crash-2022-03-27_15.27.53-server.txt](https://github.com/ExDrill/CaveEnhancementsMod/files/8357706/crash-2022-03-27_15.27.53-server.txt)

**Comment by Albertsmods** [comment]
This seems to be an issue with the mantle caves from terralith

**Comment by TheButterbrotMan** [comment]
Im experiencing the same.

https://bytebin.lucko.me/6RHP80IwSD

**Comment by outercloudstudio** [comment]
As far as I can tell this has to do with the rose quartz biome. We'll take a look into this.

**Comment by outercloudstudio** [comment]
Correction, the biome is registered.

**Comment by outercloudstudio** [comment]
I've found a potential bit of information that might help us fix this bug.

https://discord.com/channels/507304429255393322/807617588045545523/923210128155639838

**Comment by outercloudstudio** [comment]
After investigating this further is suspect this is due to conflicting mixins cause by the biome api we use. I don't believe we would be able to fix this unless we redo how biomes are registered. Due to that fact I'm closing this issue because I don't believe we will fix this too soon.

**Comment by TheButterbrotMan** [comment]
So basically you will make your mod incompatible to every other mod using TerraBlender?

Eg. Terralith?

**Comment by outercloudstudio** [comment]
No, we'll look at fixing it but I honestly don't know how to make this work. Do other terrablender mods work with terralith?

**Comment by ExDrill** [comment]
I've done some testing with BYG and it seems to work fine, I'm going to look into registering the biomes without Terrablender.

**Comment by outercloudstudio** [comment]
@TheButterbrotMan Good news. Drill has gotten mixins to work without using terrablender. It is too be seen wether this fixes the crash though.

**Comment by outercloudstudio** [comment]
With testing drill has gotten the mod to support terralith!
