### ISSUE TITLE
Cave Enhancements 1.0.2 crash with terrablender

### ISSUE THREAD

**Issue by Alec153** [ExDrill/CaveEnhancementsMod#3]
When terrablender is present the game will crash.
[crash-2022-03-30_09.44.31-client.txt](https://github.com/ExDrill/CaveEnhancementsMod/files/8381503/crash-2022-03-30_09.44.31-client.txt)

**Comment by Niketats** [comment]
same

**Comment by Niketats** [comment]
1.0.1 - crashes without terrablender
1.0.2 - crashes with terrablender

**Comment by ExDrill** [comment]
I think I know what exactly causes this to occur, thank you for reporting!

**Comment by ExDrill** [comment]
Should be fixed in 1.0.3 👍
