### ISSUE TITLE
Cave Enhancements 1.0.1 server crash

### ISSUE THREAD

**Issue by Alec153** [ExDrill/CaveEnhancementsMod#4]
Crash while exploring on a test server related to a ticking entity. I have do have a lot of mods but it seems to be only related to Cave Enhancements.
[crash-2022-03-30_12.34.58-server.txt](https://github.com/ExDrill/CaveEnhancementsMod/files/8382873/crash-2022-03-30_12.34.58-server.txt)

**Comment by ExDrill** [comment]
@outercloudstudio Can you look into this deeper, this seems to be from the big_goop_drip projectile's server packet.

**Comment by outercloudstudio** [comment]
Yep I'll take a look at fixing this!

**Comment by outercloudstudio** [comment]
I've located the fix for this. I can fix this when I get home later today as I'm currently eating lunch at school.

**Comment by outercloudstudio** [comment]
I'll close this issue after fixing it but consider it fixed.
