### ISSUE TITLE
[BUG] spamming console and probably causes memory leak

### ISSUE THREAD

**Issue by Polarite** [ExDrill/CaveEnhancementsMod#6]
![image](https://user-images.githubusercontent.com/34978332/161103290-cc419afe-5f1e-4380-8fdd-297cb9ca47ab.png)

Found out with c2me, I dont really know how system works but apperantly its related to this mod.

**Comment by ExDrill** [comment]
I'll look into this, thank you for reporting!

**Comment by ExDrill** [comment]
Alright, I've fixed it. Update should be coming out soon. Once again, thank you for reporting.
