### ISSUE TITLE
Some datapack errors on server

### ISSUE THREAD

**Issue by TheButterbrotMan** [ExDrill/CaveEnhancementsMod#7]
https://bytebin.lucko.me/AxaVMzCbaR

**Comment by TheButterbrotMan** [comment]
(make server crash)

**Comment by ExDrill** [comment]
Alright, I've located the issue and I'm rolling a hotfix that *should* fix it.

**Comment by ExDrill** [comment]
https://www.curseforge.com/minecraft/mc-mods/cave-enhancements/files/3757600
A new version is rolling out. If it's not fixed, then I'm not entirely sure what could be causing this.
If you could, please verify with me that it did. Thanks!

**Comment by TheButterbrotMan** [comment]
So, it was not present in the version before this. So smth new in new version is causing it.

**Comment by ExDrill** [comment]
version 1.1.1 has been approved, could you try it and see if it works now?

**Comment by TheButterbrotMan** [comment]
Having another one now. https://bytebin.lucko.me/dbAalcrert

**Comment by ExDrill** [comment]
This seems to be an issue with Incendium! But it seems like Cave Enhancements is no longer producing any issues, thank you for the report!
